Notifikasjons-prikk ved nytt mål
navikt/aktivitetsplan pull request #633
Opened 2020-09-17 11:37 UTC by theagilepadawan

- Skrevet om reducer til TypeScript
- Lagt til 'Lest' i Redux-storen
- Abstrahert notifikasjonsprikk ut i egen komponent og gjort om logikken også i aktivitetskorts-notifikasjoner

2020-09-17 13:30 UTC, hakonph requested changes

2020-09-18 07:31 UTC, alexander-svendsen commented on src/felles-komponenter/utils/visible-if-notifikasjon.less
> +
Vi har egentlig litt som mål å gå helt over til å bruke less modules. Så når vi lager nye så er det ganske fint at de blir dette ja :)

2020-09-18 07:31 UTC, alexander-svendsen commented on src/moduler/aktivitet/aktivitet-util.ts
> +        //Hvis aktivitetsplanen har blitt lest noensinne
Blir vel mer rett å skrive: 
Hvis aktivitetsplanen ikke har blitt lest noensinne

men jeg er litt mer fan av beskrivende variabler enn kommentarer i koden, så hva med å ta ut variablen 

`const aldriLestAktivitetsplanen = !lestInformasjon`

2020-09-18 09:27 UTC, alexander-svendsen approved these changes

2020-09-18 09:38 UTC, hakonph approved these changes

2020-09-18 11:36 UTC, merged