Visning av feilmelding når aktivitetskort ikke er flyttbart + refaktorering
navikt/aktivitetsplan pull request #642
Opened 2020-10-12 11:25 UTC by theahj

Som bruker og veileder som ser aktivitetsplanen på desktop
ønsker jeg å få informasjon om hvorfor jeg ikke kan drag&drop aktivitetskort
slik at jeg kan forstå hvorfor drag&drop ikke fungerer for dette aktivitetskortet

2020-10-12 14:01 UTC, alexander-svendsen approved these changes

2020-10-13 06:56 UTC, hakonph requested changes

2020-10-13 06:56 UTC, hakonph commented on src/moduler/aktivitet/aktivitet-kort/AktivitetskortPeriode.tsx
> +    return <Normaltekst id={id}>{periodeVisning()}</Normaltekst>;
bruker vi denne iden til noe? 
vet vi at vi ikke bruker aktivitet id til id et annet sted?

2020-10-13 06:56 UTC, hakonph commented on src/moduler/aktivitet/aktivitet-kort/AktivitetskortTittel.tsx
> +            <Element tag="h1" id={id} className={classNames(styles.tittel, 'softbreak')}>
mistenker at denne også er aktivitetsiden?

2020-10-13 06:56 UTC, hakonph commented on src/moduler/aktivitet/aktivitet-kort/SokeAvtaleAntall.tsx
> +            <VisibleIfDiv visible={antallStillingerSokes && antallStillingerSokes > 0}>
fjern  && antallStillingerSokes 
eventuelt leg på !!

2020-10-13 06:56 UTC, hakonph commented on src/moduler/aktivitet/aktivitet-kort/AktivitetskortTillegg.tsx
> +        <HiddenIfDiv hidden={!(avtalt || !!etikett || !!dialog)} className={styles.tillegg}>
return null og vanlig div

2020-10-13 07:45 UTC, hakonph approved these changes

2020-10-13 08:13 UTC, merged