Fho ny
navikt/aktivitetsplan pull request #702
Opened 2021-01-18 13:26 UTC by hakonph

2021-01-18 14:23 UTC, theahj commented
![](https://github.trello.services/images/mini-trello-icon.png) [1 vise fho. inni aktivitetskort - START HER](https://trello.com/c/zKRuplop/132-1-vise-fho-inni-aktivitetskort-start-her)

2021-01-18 15:10 UTC, izisfro requested changes
Er noe feil med renamingen av filer og har blitt med en tom fil, også er det noe feil med når forhåndsorientering comboboxen vises som må fikses, ellers ser det bra ut. Resten er litt småplukk

2021-01-19 07:51 UTC, hakonph commented on src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltInfotekst.tsx
> +        <>
tremnger denne pga <DeleLinje />

2021-01-19 07:55 UTC, hakonph commented on src/moduler/aktivitet/visning/avtalt-container-gammel/AvtaltForm.tsx
> +const validateForhandsorienter = (val: string, values: { avtaltSelect?: string }): string | undefined => {
jepp. alt under avtalt-container-gammel  er bare coppy pasete

2021-01-19 08:05 UTC, hakonph commented on src/moduler/aktivitet/visning/avtalt-container/AvtaltContainer.tsx
> +    avtaltSelect: string;
likte forhaandsorienteringType

2021-01-19 08:07 UTC, hakonph commented on src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsMelding.tsx
> +                <Normaltekst className="blokk-xs">
Trenger det. Legger på en del luft.
Burde kanskje skrive det om lit?

2021-01-19 08:56 UTC, izisfro commented on src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsMelding.tsx
> +                <Normaltekst className="blokk-xs">
Liker ikke så godt å legge på felleskomponentklassene.. bedre med css modules, men ser det var sånn fra før av så er ikke så farlig

2021-01-19 10:55 UTC, izisfro approved these changes
Ser bra ut. Det ble litt feil nå med at knappenavnet ikke tar høyde for at verdien kan være ikke satt men jeg fikser det samtidig som jeg legger på typer i ny pr

2021-01-19 11:02 UTC, merged