Legge inn nytt eskaleringsvarsel fra dialog
navikt/aktivitetsplan pull request #902
Opened 2022-03-23 14:17 UTC by theahj

2022-03-23 14:18 UTC, theahj commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endre 'Eskaleringsvarsel' i aktivitetsplan til å hente fra veilarbdialog](https://trello.com/c/mlVRXUuH/522-endre-eskaleringsvarsel-i-aktivitetsplan-til-%C3%A5-hente-fra-veilarbdialog)

2022-03-24 13:37 UTC, holymaloney approved these changes

2022-03-25 09:02 UTC, holymaloney requested changes
Varselbanner dukker ikke opp for eksternbruker i dev

2022-03-30 13:37 UTC, holymaloney approved these changes

2022-03-30 13:38 UTC, merged