Bruker veilarbperson v2 endepunkt
navikt/aktivitetsplan pull request #915
Opened 2022-05-31 12:59 UTC by stianStensli

2022-05-31 13:08 UTC, holymaloney commented
![](https://github.trello.services/images/mini-trello-icon.png) [Aktivitetsplan må over på veilarbperson v2-endepunkt](https://trello.com/c/PrQxyN0J/569-aktivitetsplan-m%C3%A5-over-p%C3%A5-veilarbperson-v2-endepunkt)

2022-05-31 14:09 UTC, stianStensli commented
Fnr er et query  parameter, jeg kan oppdatere det i morgen

2022-06-02 12:23 UTC, holymaloney requested changes
Vi har dessverre behov for bostedsadresse i aktivitetsplan

2022-06-07 14:05 UTC, holymaloney approved these changes

2022-06-07 14:09 UTC, merged